# Generated by Django 3.1.3 on 2020-11-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
