# Generated by Django 3.1.3 on 2020-12-04 06:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_diary_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='analysis',
        ),
        migrations.AddField(
            model_name='diary',
            name='spectrum',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2),
        ),
    ]
